### ISSUE TITLE
[1.19.2] Crashes on startup due to a Functional Storage update

### ISSUE THREAD

**Issue by vizthex123** [Mrthomas20121-Mods/Functional-Storage-Extra#6]
Seems like the mod changed the internal reference to wood types, which causes this to crash.

Log:
[latest.log](https://github.com/Mrthomas20121-Mods/Functional-Storage-Extra/files/13061345/latest.log)

**Comment by Mrthomas20121** [comment]
i'm aware of it and i'm working on a fix
